# Generated by Django 2.1.7 on 2019-03-22 21:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
            ],
            options={
                'managed': False,
                'base_manager_name': 'base_objects',
            },
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField()),
                ('b_set', models.ManyToManyField(db_constraint=False, related_name='a_set', to='test07_m2m_one.B')),
            ],
        ),
        migrations.CreateModel(
            name='B0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
