language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0.*
  - DJANGO_VERSION=2.1.*
  - DJANGO_VERSION=2.2.*

install:
  - pip install -U pip setuptools
  - pip install -U "Django==${DJANGO_VERSION}"
  - pip install -e .[ci]

script:
  - cd tests && pytest --cov --cov-report term

after_success:
  - coveralls
