language: python

python:
  - "3.6"

cache: pip

services:
  - postgresql

env:
  - DJANGO_VERSION=2.0.*
  - DJANGO_VERSION=2.1.*
  - DJANGO_VERSION=2.2.*

install:
  - pip install -U pip setuptools
  - pip install -U "Django==${DJANGO_VERSION}"
  - pip install -e .[ci]

before_script:
  - psql -c 'CREATE DATABASE django_outer_join_test;' -U postgres
  - cd tests

script:
  - ./test-makemigrations.sh
  - pytest --cov --cov-report term

after_success:
  - coveralls
