# Generated by Django 2.1.7 on 2019-03-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test04_fk_out', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a0',
            name='val',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='a1',
            name='val',
            field=models.IntegerField(null=True),
        ),
    ]
