# Generated by Django 2.1.7 on 2019-03-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique=True)),
                ('b', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_set', to='test05_fk_in.B')),
            ],
        ),
        migrations.CreateModel(
            name='B0',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B1',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('val', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
