# Generated by Django 2.1.7 on 2019-03-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='A0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.IntegerField()),
                ('key2', models.IntegerField()),
                ('field1', models.IntegerField()),
                ('field2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='A1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.IntegerField()),
                ('key2', models.IntegerField()),
                ('field1', models.IntegerField(null=True)),
                ('field3', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='a1',
            unique_together={('key1', 'key2')},
        ),
        migrations.AlterUniqueTogether(
            name='a0',
            unique_together={('key1', 'key2')},
        ),
    ]
