# Generated by Django 2.1.8 on 2019-04-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test03_multi_on', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='test03_multi_on.A')),
            ],
        ),
    ]
