# Generated by Django 2.1.7 on 2019-03-22 23:13

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
            ],
            options={
                'managed': False,
                'base_manager_name': 'base_objects',
            },
        ),
        migrations.CreateModel(
            name='B',
            fields=[
            ],
            options={
                'managed': False,
                'base_manager_name': 'base_objects',
            },
        ),
        migrations.CreateModel(
            name='Through',
            fields=[
            ],
            options={
                'managed': False,
                'base_manager_name': 'base_objects',
            },
        ),
        migrations.CreateModel(
            name='A0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='A1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.IntegerField(unique=True)),
                ('val', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Through0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                        to='test08_m2m_all.A0')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                        to='test08_m2m_all.B0')),
            ],
        ),
        migrations.CreateModel(
            name='Through1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('a',
                 models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='test08_m2m_all.A')),
                ('b',
                 models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='test08_m2m_all.B')),
            ],
        ),
        migrations.AddField(
            model_name='a0',
            name='b_set',
            field=models.ManyToManyField(related_name='a_set', through='test08_m2m_all.Through0',
                                         to='test08_m2m_all.B0'),
        ),
        migrations.AlterUniqueTogether(
            name='through1',
            unique_together={('a', 'b')},
        ),
        migrations.AlterUniqueTogether(
            name='through0',
            unique_together={('a', 'b')},
        ),
    ]
