# Generated by Django 2.1.8 on 2019-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('field1', models.IntegerField(null=True)),
                ('field2', models.IntegerField(null=True)),
                ('field3', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='A0',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('field1', models.IntegerField()),
                ('field2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='A1',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('field1', models.IntegerField(null=True)),
                ('field3', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
